Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GallaryPortal.Models;
using IdentitySample.Models;
using System.IO;

namespace GallaryPortal.Controllers
{
    public class GalleryController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Gallery
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Fashion()
        {
            return View();
        }
        public ActionResult Nude()
        {
            return View();
        }
        public ActionResult ConcentArt()
        {
            return View();
        }
        public ActionResult Celebritiese()
        {
            return View();
        }

        public async Task<JsonResult> GetLastGalleries()
        {
            List<Gallery> AllGallaries = new List<Gallery>();
            db.Configuration.ProxyCreationEnabled = false;
            AllGallaries = db.galleries.OrderByDescending(x => x.id).Take(5).ToList();
            return new JsonResult { Data = AllGallaries, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public async Task<ActionResult> CatId(int? id)
        {
            List<Gallery> Gallery = new List<Gallery>();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gallery = db.galleries.Where(x => x.Category == id).ToList();
            if (Gallery == null)
            {
                return HttpNotFound();
            }
            return new JsonResult { Data = Gallery, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public async Task<ActionResult> Banners()
        {
            List<Gallery> Gallery = new List<Gallery>();

            Gallery = db.galleries.Where(x => x.Category == 6 && x.ActivePassive == true).ToList();
            if (Gallery == null)
            {
                return HttpNotFound();
            }
            return new JsonResult { Data = Gallery, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

    }
}

Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin")) {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mohammad Mousavi</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.css" integrity="sha512-UTNP5BXLIptsaj5WdKFrkFov94lDx+eBvbKyoe1YAfjeRPC+gT5kyZ10kOHCfNZqEui1sxmqvodNUx3KbuYI/A==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.css" integrity="sha512-OTcub78R3msOCtY3Tc6FzeDJ8N9qvQn1Ph49ou13xgA9VsH9+LRxoFU6EqLhW4+PKRfU+/HReXmSZXHEkpYoOA==" crossorigin="anonymous" />
    <link href="~/Content/slicknav.css" rel="stylesheet" />
    <link href="~/Content/flaticon.css" rel="stylesheet" />
    <link href="~/Content/animate.min.css" rel="stylesheet" />
    <link href="~/Content/magnific-popup.css" rel="stylesheet" />
    <link href="~/Content/fontawesome-all.min.css" rel="stylesheet" />
    <link href="~/Content/themify-icons.css" rel="stylesheet" />
    <link href="~/Content/slick.css" rel="stylesheet" />
    <link href="~/Content/nice-select.css" rel="stylesheet" />
    <link href="~/Content/style.css" rel="stylesheet" />
    <link href="~/Content/aos.css" rel="stylesheet" />

    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@


</head>
<body>
    <!--? Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    @*<img src="~/img/logo/loader.gif" alt="">*@
                    <p style="font-size:.7rem;font-weight:bold">Loading...</p>
                </div>
            </div>
        </div>
    </div>

    @Html.Partial("_PartialMenu")

    <!-- Single Slider -->

    <div class="container-fluid">
        <div class="row">
            <div id="carouselExampleControls" class="carousel slide carousel-fade" data-ride="carousel">
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

        </div>
    </div>


    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer>
        <!--? Footer Start-->
        <div class="footer-area footer-bg">
            <div class="container">

                <div class="footer-bottom">
                    <div class="row d-flex justify-content-between align-items-center" style="flex-direction: column-reverse;">
    
                        <row>
                            <div class="col-md-12 pt-2">
                                <div class="footer-copy-right">
                                    <p>
                                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                        Copyright &copy;
                                        <script>document.write(new Date().getFullYear());</script> All rights reserved
                                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                    </p>
                                </div>
                            </div>

                        </row>
                        <row>
                            <div class="col-md-12">
                                <!-- Footer Social -->
                                <div class="footer-social f-right">
                                    <span>Follow Us</span>
                                    <a href="#"><i class="fab fa-twitter"></i></a>
                                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                                    <a href="#"><i class="fas fa-globe"></i></a>
                                    <a href="#"><i class="fab fa-instagram"></i></a>
                                </div>
                            </div>

                        </row>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End-->
    </footer>
    <!-- Scroll Up -->
    <div id="back-top">
        <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
    </div>
    <script src="~/Scripts/vendor/modernizr-3.5.0.min.js"></script>
    <script src="~/Scripts/vendor/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/site.js" asp-append-version="true"></script>

    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <!-- Jquery Mobile Menu -->
    <script src="~/Scripts/jquery.slicknav.min.js"></script>
    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.js" integrity="sha512-gY25nC63ddE0LcLPhxUJGFxa2GoIyA5FLym4UJqHDEMHjp8RET6Zn/SHo1sltt3WuVtqfyxECP38/daUc/WVEA==" crossorigin="anonymous"></script>
    <script src="~/Scripts/slick.min.js"></script>
    <!-- One Page, Animated-HeadLin -->
    <script src="~/Scripts/wow.min.js"></script>
    <script src="~/Scripts/animated.headline.js"></script>
    <script src="~/Scripts/jquery.magnific-popup.js"></script>
    <!-- Nice-select, sticky -->
    <script src="~/Scripts/jquery.nice-select.min.js"></script>
    <script src="~/Scripts/jquery.sticky.js"></script>
    <!-- contact js -->
    <script src="~/Scripts/contact.js"></script>
    <script src="~/Scripts/jquery.form.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/mail-script.js"></script>
    <script src="~/Scripts/jquery.ajaxchimp.min.js"></script>
    <!-- Jquery Plugins, main Jquery -->
    <script src="~/Scripts/plugins.js"></script>
    <script src="~/Scripts/aos.js"></script>
    <script src="~/Scripts/main.js"></script>

    <script>
        $(document).ready(function () {
            var arr = []
            $.ajax({
                type: "GET",
                url:"@Url.Action("Banners", "Gallery")",
                success: function(response)
                {
                    arr = response
                    var htmlString = '';
                    htmlString += '<div class="carousel-inner">'
                        for(i=0; i< arr.length; i++)
                        {
                            htmlString += '<div class="carousel-item"><img src="' + arr[i].imgUrl + '" class="d-block w-100" alt="..."> </div>'
                        }
                    htmlString += '</div>'

                    $(htmlString).insertBefore( ".carousel-control-prev" );
                    $('.carousel-inner').each(function(){
                        $(this).find('.carousel-item').eq(0).addClass('active');
                    });

                }
            });

        });
    </script>



    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutGallery.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/fonts/icomoon/style.css" rel="stylesheet" />
    <link href="~/Content/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/Content/owl.theme.default.min.css" rel="stylesheet" />
    <link href="~/Content/lightgallery.min.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/slicknav.css" rel="stylesheet" />
    <link href="~/Content/flaticon.css" rel="stylesheet" />
    <link href="~/Content/animate.min.css" rel="stylesheet" />
    <link href="~/Content/magnific-popup.css" rel="stylesheet" />
    <link href="~/Content/fontawesome-all.min.css" rel="stylesheet" />
    <link href="~/Content/themify-icons.css" rel="stylesheet" />
    <link href="~/Content/swiper.css" rel="stylesheet" />
    <link href="~/Content/slick.css" rel="stylesheet" />
    <link href="~/Content/aos.css" rel="stylesheet" />
    <link href="~/Content/nice-select.css" rel="stylesheet" />
    <link href="~/Content/style.css" rel="stylesheet" />






</head>
<body>


    <!--? Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    @*<img src="~/img/logo/loader.gif" alt="">*@
                    <p style="font-size:.7rem;font-weight:bold">Loading...</p>
                </div>
            </div>
        </div>
    </div>

    @Html.Partial("_PartialMenu")

    <div>
        @RenderBody()
    </div>


    <footer>
        <!--? Footer Start-->
        <div class="footer-area footer-bg">
            <div class="container">

                <div class="footer-bottom">
                    <div class="row d-flex justify-content-between align-items-center" style="flex-direction: column-reverse;">

                        <row>
                            <div class="col-md-12 pt-2">
                                <div class="footer-copy-right">
                                    <p>
                                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                        Copyright &copy;
                                        <script>document.write(new Date().getFullYear());</script> All rights reserved
                                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                    </p>
                                </div>
                            </div>

                        </row>
                        <row>
                            <div class="col-md-12">
                                <!-- Footer Social -->
                                <div class="footer-social f-right">
                                    <span>Follow Us</span>
                                    <a href="#"><i class="fab fa-twitter"></i></a>
                                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                                    <a href="#"><i class="fas fa-globe"></i></a>
                                    <a href="#"><i class="fab fa-instagram"></i></a>
                                </div>
                            </div>

                        </row>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End-->
    </footer>
    <!-- Scroll Up -->
    <div id="back-top">
        <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
    </div>


    <script src="~/Scripts/vendor/modernizr-3.5.0.min.js"></script>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery-ui.js"></script>


    <script src="~/Scripts/site.js" asp-append-version="true"></script>

    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    <!-- Jquery Mobile Menu -->
    <script src="~/Scripts/jquery.slicknav.min.js"></script>
    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="~/Scripts/owl.carousel.min.js"></script>
    <script src="~/Scripts/slick.min.js"></script>
    <!-- One Page, Animated-HeadLin -->
    <script src="~/Scripts/wow.min.js"></script>
    <script src="~/Scripts/animated.headline.js"></script>
    <script src="~/Scripts/jquery.magnific-popup.js"></script>
    <!-- Nice-select, sticky -->
    <script src="~/Scripts/jquery.nice-select.min.js"></script>
    <script src="~/Scripts/jquery.sticky.js"></script>
    <script src="~/Scripts/jquery.stellar.min.js"></script>
    <script src="~/Scripts/jquery.magnific-popup.min.js"></script>
    <script src="~/Scripts/swiper.min.js"></script>
    <script src="~/Scripts/lightgallery-all.min.js"></script>
    <script src="~/Scripts/aos.js"></script>
    <!-- contact js -->
    <script src="~/Scripts/contact.js"></script>
    <script src="~/Scripts/jquery.form.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/mail-script.js"></script>
    <script src="~/Scripts/jquery.ajaxchimp.min.js"></script>
    <!-- Jquery Plugins, main Jquery -->


    <script src="~/Scripts/picturefill.min.js"></script>
    <script src="~/Scripts/lightgallery-all.min.js"></script>
    <script src="~/Scripts/jquery.mousewheel.min.js"></script>
    <script src="~/Scripts/plugins.js"></script>
    <script src="~/Scripts/main.js"></script>

    @RenderSection("Scripts", required: false)







</body>
</html>

Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <title>@ViewBag.Title</title>

    <!-- Custom fonts for this template-->
    <link href="~/Areas/Cp/Content/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Areas/Cp/Content/css/sb-admin-2.min.css" rel="stylesheet" />
</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6 p-5">
                                @RenderBody()

                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Areas/Cp/Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Areas/Cp/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Areas/Cp/Content/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Areas/Cp/Content/js/sb-admin-2.min.js"></script>

</body>

</html>

Views/Shared/_LayoutVideo.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mohammad Mousavi</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css" integrity="sha512-Velp0ebMKjcd9RiCoaHhLXkR1sFoCCWXNp6w4zj1hfMifYB5441C+sKeBl/T/Ka6NjBiRfBBQRaQq65ekYz3UQ==" crossorigin="anonymous" />
    <link href="~/Content/slicknav.css" rel="stylesheet" />
    <link href="~/Content/flaticon.css" rel="stylesheet" />
    <link href="~/Content/animate.min.css" rel="stylesheet" />
    <link href="~/Content/magnific-popup.css" rel="stylesheet" />
    <link href="~/Content/fontawesome-all.min.css" rel="stylesheet" />
    <link href="~/Content/themify-icons.css" rel="stylesheet" />
    <link href="~/Content/slick.css" rel="stylesheet" />
    <link href="~/Content/nice-select.css" rel="stylesheet" />
    <link href="~/Content/style.css" rel="stylesheet" />
    <link href="~/Content/aos.css" rel="stylesheet" />
</head>
<body>
    <!--? Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <p style="font-size:.7rem;font-weight:bold">Loading...</p>
                </div>
            </div>
        </div>
    </div>


    @Html.Partial("_PartialMenu")


    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer>
        <!--? Footer Start-->
        <div class="footer-area footer-bg">
            <div class="container">

                <div class="footer-bottom">
                    <div class="row d-flex justify-content-between align-items-center" style="flex-direction: column-reverse;">

                        <row>
                            <div class="col-md-12 pt-2">
                                <div class="footer-copy-right">
                                    <p>
                                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                        Copyright &copy;
                                        <script>document.write(new Date().getFullYear());</script> All rights reserved
                                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                    </p>
                                </div>
                            </div>

                        </row>
                        <row>
                            <div class="col-md-12">
                                <!-- Footer Social -->
                                <div class="footer-social f-right">
                                    <span>Follow Us</span>
                                    <a href="#"><i class="fab fa-twitter"></i></a>
                                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                                    <a href="#"><i class="fas fa-globe"></i></a>
                                    <a href="#"><i class="fab fa-instagram"></i></a>
                                </div>
                            </div>

                        </row>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End-->
    </footer>
    <!-- Scroll Up -->
    <div id="back-top">
        <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
    </div>
    <script src="~/Scripts/vendor/modernizr-3.5.0.min.js"></script>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/site.js" asp-append-version="true"></script>

    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <!-- Jquery Mobile Menu -->
    <script src="~/Scripts/jquery.slicknav.min.js"></script>
    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="~/Scripts/aos.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.min.js"></script>

    <script src="~/Scripts/picturefill.min.js"></script>
    <script src="~/Scripts/lightgallery-all.min.js"></script>
    <script src="~/Scripts/jquery.mousewheel.min.js"></script>
    <script src="~/Scripts/plugins.js"></script>
    <script src="~/Scripts/main.js"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_PartialContact.cshtml
<style>
    .frame-borderLess {
        box-shadow: 0 0 5px rgba(255,255,255,.5);
        border-radius: 15px;
    }

        .frame-borderLess i {
            margin-top: 2rem;
            color: #f04e3c;
            font-size: 5rem;
            text-shadow: 0px 2px 5px rgba(255,255,255,.5);
        }
        .frame-borderLess:hover {
            box-shadow: 0 0 10px rgba(255,255,255,.5);
            border: 1px solid #f04e3c;
        }
</style>


<div class="row">
    <div class="col-md-4 text-center p-3">
        <div class="frame-borderLess p-2">
            <i class="far fa-envelope"></i>
            <h6 class="mt-5 mb-5"> Email : info@mohammadmousavi.com</h6>
        </div>
    </div>
    <div class="col-md-4 text-center p-3">
        <div class="frame-borderLess p-2">
            <i class="fa fa-phone"></i>
            <h6 class="mt-5 mb-5"> Contact Number : +90 538 043 5565</h6>
        </div>
    </div>
    <div class="col-md-4 text-center p-3">
        <div class="frame-borderLess p-2">
            <i class="fab fa-whatsapp"></i>
            <h6 class="mt-5 mb-5"> whatsapp : +90 530 744 4444</h6>
        </div>
    </div>
</div>

Views/Shared/_PartialMenu.cshtml
<header>
    <!--? Header Start -->
    <div class="header-area header-transparent">
        <div class="main-header  header-sticky">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <!-- Logo -->
                    <div class="col-xl-2 col-lg-2 col-md-1">
                        <div class="logo">
                            <a href="/"><img src="~/img/logo/logo.png" alt=""></a>
                        </div>
                    </div>
                    <div class="col-xl-10 col-lg-10 col-md-10">
                        <div class="menu-main d-flex align-items-center justify-content-end">
                            <!-- Main-menu -->
                            <div class="main-menu f-right d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li><a href="/">Home</a></li>
                                        <li><a href="/Portfolio">Portfolio</a></li>
                                        <li>
                                            <a href="#">Gallery</a>
                                            <ul class="submenu">
                                                <li><a href="/Gallery/Fashion">Fashion</a></li>
                                                <li><a href="/Gallery/Nude">Nude</a></li>
                                                <li><a href="/Gallery/ConcentArt">Art</a></li>
                                                <li><a href="/Gallery/Celebritiese">Celebrities</a></li>
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="/VideoGallery">Video</a>
                                        </li>
                                        <li><a href="/Contact">Contact</a></li>
                                    </ul>
                                </nav>
                            </div>
                            @*<div class="header-right-btn f-right d-none d-lg-block ml-20">
                                    <a href="contact.html" class="btn header-btn">Contact now</a>
                                </div>*@
                        </div>
                    </div>
                    <!-- Mobile Menu -->
                    <div class="col-12">
                        <div class="mobile_menu d-block d-lg-none"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->
</header>