Models/videoGallery.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GallaryPortal.Models
{
    public class videoGallery
    {
        [Key]
        public int id { get; set; }

        [Required(ErrorMessage ="This Filed is Mandetory")]
        [Display(Name = "Video Name")]
        public string VideoName { get; set; }

        [Required(ErrorMessage = "This Filed is Mandetory")]
        [Display(Name = "YouTube Video ID")]
        public string VideoID { get; set; }
        [Display(Name ="Active/Inactive")]
        public bool Actice { get; set; }

    }
}

Areas/Cp/Controllers/videoGalleriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GallaryPortal.Models;
using IdentitySample.Models;

namespace GallaryPortal.Areas.Cp.Controllers
{
    public class videoGalleriesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize]

        // GET: Cp/videoGalleries
        public async Task<ActionResult> Index()
        {
            return View(await db.videoGalleries.ToListAsync());
        }

        [Authorize]

        // GET: Cp/videoGalleries/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            videoGallery videoGallery = await db.videoGalleries.FindAsync(id);
            if (videoGallery == null)
            {
                return HttpNotFound();
            }
            return View(videoGallery);
        }
        [Authorize]

        // GET: Cp/videoGalleries/Create
        public ActionResult Create()
        {
            return View();
        }
        [Authorize]

        // POST: Cp/videoGalleries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,VideoName,VideoID,Actice")] videoGallery videoGallery)
        {
            if (ModelState.IsValid)
            {
                db.videoGalleries.Add(videoGallery);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(videoGallery);
        }
        [Authorize]

        // GET: Cp/videoGalleries/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            videoGallery videoGallery = await db.videoGalleries.FindAsync(id);
            if (videoGallery == null)
            {
                return HttpNotFound();
            }
            return View(videoGallery);
        }
        [Authorize]

        // POST: Cp/videoGalleries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,VideoName,VideoID,Actice")] videoGallery videoGallery)
        {
            if (ModelState.IsValid)
            {
                db.Entry(videoGallery).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(videoGallery);
        }
        [Authorize]

        // GET: Cp/videoGalleries/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            videoGallery videoGallery = await db.videoGalleries.FindAsync(id);
            if (videoGallery == null)
            {
                return HttpNotFound();
            }
            return View(videoGallery);
        }
        [Authorize]

        // POST: Cp/videoGalleries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            videoGallery videoGallery = await db.videoGalleries.FindAsync(id);
            db.videoGalleries.Remove(videoGallery);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/VideoGalleryController.cs
using IdentitySample.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GallaryPortal.Models;
using System.Threading.Tasks;

namespace GallaryPortal.Controllers
{
    public class VideoGalleryController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: VideoGallery
        public ActionResult Index()
        {
            return View();
        }

        public async Task<JsonResult> GetAllVideo()
        {
            List<videoGallery> AllVideo = new List<videoGallery>();
            db.Configuration.ProxyCreationEnabled = false;
            AllVideo = db.videoGalleries.OrderByDescending(x => x.id).ToList();
            return new JsonResult { Data = AllVideo, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
    }
}

Areas/Cp/Views/videoGalleries/Create.cshtml
@model GallaryPortal.Models.videoGallery

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Cp/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>videoGallery</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.VideoName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VideoID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Actice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Actice)
                    @Html.ValidationMessageFor(model => model.Actice, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Areas/Cp/Views/videoGalleries/Delete.cshtml
@model GallaryPortal.Models.videoGallery

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Cp/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>videoGallery</h4>
    <hr />
    <dl class="dl-horizontal">

        <dd>
            <img class="img-fluid" src="https://img.youtube.com/vi/@Url.Content(Model.VideoID)/hqdefault.jpg" style="border-radius:5px; box-shadow:0 0 5px rgba(0,0,0,.3)" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VideoName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VideoName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Actice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Actice)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Areas/Cp/Views/videoGalleries/Details.cshtml
@model GallaryPortal.Models.videoGallery

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Cp/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>videoGallery</h4>
    <hr />
    <dl class="dl-horizontal">
        <dd>
            <img class="img-fluid" src="https://img.youtube.com/vi/@Url.Content(Model.VideoID)/hqdefault.jpg" style="border-radius:5px; box-shadow:0 0 5px rgba(0,0,0,.3)" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VideoName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VideoName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Actice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Actice)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Areas/Cp/Views/videoGalleries/Edit.cshtml
@model GallaryPortal.Models.videoGallery

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Cp/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>videoGallery</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.VideoName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VideoID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Actice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Actice)
                    @Html.ValidationMessageFor(model => model.Actice, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Areas/Cp/Views/videoGalleries/Index.cshtml
@model IEnumerable<GallaryPortal.Models.videoGallery>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Cp/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>

<p>
    <a class="btn btn-success btn-sm" href="@Url.Action("Create", "videoGalleries")">New Item</a>
</p>
<div class="table-responsive">
    <table class="table table-striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.VideoName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VideoID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Actice)
            </th>
            <th>

            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.VideoName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VideoID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Actice)
        </td>
        <td>
            <img src="https://img.youtube.com/vi/@Url.Content(item.VideoID)/hqdefault.jpg" style="max-width:50px; border-radius:5px; box-shadow:0 0 5px rgba(0,0,0,.3)" />
        </td>
        <td>
            <a class="btn btn-info btn-sm" href="@Url.Action("Edit", "videoGalleries", new { id = item.id })">Edit</a>
            <a class="btn btn-success btn-sm" href="@Url.Action("Details", "videoGalleries", new { id = item.id })">Detail</a>
            <a class="btn btn-danger btn-sm" href="@Url.Action("Delete", "videoGalleries", new { id = item.id })">Delete</a>
        </td>
    </tr>
        }

    </table>
</div>